---
title: "Schedule & Materials"
format: html
toc: true
---

This is the official course schedule. Slides/notes are typically posted **before each lecture**.

---

## Week 1

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **Jan 11** | **Course overview** <br> Introduction to control | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQCLrKx8SV7nRatIEg14Lga3AUlufldg3FP_3wStS32hh2g?e=JMTpfS){.btn .btn-sm .btn-outline-primary} <br> Reading: 1.1-1.6|  |
| **Jan 13** | **Dynamic systems** <br> Differential equations | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQBAQLRx2k-7Rbf7gXkddfpMAXsaswGlkLTVF4pBrJ0QqZM?e=6Tgcy7){.btn .btn-sm .btn-outline-primary} <br> Reading: 2.1-2.2 |  |
| **Jan 15** | **Laplace review** <br> Diff eqs → Laplace transforms | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQDlLApAhYr2T7zfb10yrI0EAfTePA28dwKQpMarlMUMtLk?e=xOLAW3){.btn .btn-sm .btn-outline-primary} <br> Reading: 2.4 |  |

---

## Week 2

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **Jan 18** | **Laplace review (cont.)** <br> Properties and examples | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQCqHmzW8htnQrLEkCE82mGoAVeW57i7yEqLwf51ud7rCdY?e=9j0owZ){.btn .btn-sm .btn-outline-primary} <br> Reading: 2.4|  |
| **Jan 20** | **Modeling** <br> DC motor modeling | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQCaJUYV0FZwT5nDjchM-4bBAWCPGI4NzXxMyZONF4uhYr0?e=ATweZE){.btn .btn-sm .btn-outline-primary} <br> Reading: 2.5|  |
| **Jan 22** | **Modeling** <br> Mechanical systems | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQAe1tqyVfGGSLjLO40Qi5GjAXsblzWSI3xrv5jSZUVpg84?e=MZCybh){.btn .btn-sm .btn-outline-primary} <br> Reading: 2.3,2.5| [HW1 out](homework.qmd){.btn .btn-sm .btn-warning} |

---

## Week 3

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **Jan 25** | **Modeling** <br> Block Diagrams | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQAJxHss2IFMSIsZKCS1v8TMAf4wn8SkstPx9n_IgKgHGNo?e=GBgGlM){.btn .btn-sm .btn-outline-primary} <br> Reading: 2.6| |
| **Jan 27** | **Analysis** <br> Openloop Control | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQAx6yZLcZy1RZ_1HuUFxQrrAVDbKsCHNBvdpaJg5Yyb19A?e=mhML1R){.btn .btn-sm .btn-outline-primary} <br> Reading: 4.1-4.2 | |
| **Jan 29** | **Analysis** <br> Feedback Control | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQDbnMSMRZQdSKuqbTCsWAgrAfaAQutdUnvhFTfMWmXIB_g?e=IVr4wz){.btn .btn-sm .btn-outline-primary} <br> Reading: 4.3 | |

---

## Week 4

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **Feb 1** | **Analysis** <br> Sensitivity I | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQCAlzR-yGcZS4BNLixQtuGPAWdS5AwTuYen4ItSyFxTnNo?e=eFTLgE){.btn .btn-sm .btn-outline-primary} <br> Reading: 4.4, 4.5| [HW1 Sol out](homework.qmd){.btn .btn-sm .btn-warning} |
| **Feb 3** | **Quiz + Review**  |  | [Quiz 1](#){.btn .btn-sm .btn-warning .disabled role="button" aria-disabled="true"} |
| **Feb 5** | **Analysis** <br> Sensitivity II + Steady State Error​ | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQBD9k48xnKSRa72UwP2XWryAV3ebOoNc8LmJQ0_-Q3lD8Q?e=a9TXd0){.btn .btn-sm .btn-outline-primary} <br> Reading: 4.6| [HW2 out](homework.qmd){.btn .btn-sm .btn-warning} |

## Week 5

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **Feb 8** | **State Space** · Modelling | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQDkb7ELfTQhRb4xJop5vZ8jAbw0sdy0p6p6y49X3iUIt-M?e=kcaW9T){.btn .btn-sm .btn-outline-primary} <br> Reading: 3.1,3.3| |
| **Feb 10** | **State Space** · Modelling II | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQC7jWW12l5gT6z9eUXqgECrAUqodFjQP2DA9Z_ovC4q-Mc?e=g26VsQ){.btn .btn-sm .btn-outline-primary} <br> Reading: 3.4 - 3.6| |
| **Feb 12** | **State Space** · Modelling III | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQAq3BjvfNzOQL2fZdLdbrooAXUdVAirtHvvM2dlA3Kg7bw?e=lWbtXX){.btn .btn-sm .btn-outline-primary} <br> Reading: 3.7,3.9 | |

## Week 6

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **Feb 15** | **State Space** · Modelling IV | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQBlW3o8y0mbSrTx8_PWLIu0ATMayHuxMXOY8LnBPKfER6A?e=fP2pH7){.btn .btn-sm .btn-outline-primary} <br> Reading: 3.2| |
| **Feb 17** | **** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary} |[Quiz 2](#){.btn .btn-sm .btn-warning .disabled role="button" aria-disabled="true"} |
| **Feb 19** | **** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary} | |

## Week 7

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **Feb 22** | **** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary}|
| **Feb 24** | **Time Domain Analysis** · I | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQDLbCe1D-sNQ7M6LoiXct0hARY9nwPyHvVvnsi6ioF42-A?e=e17hol){.btn .btn-sm .btn-outline-primary} | |
| **Feb 26** | **Time Domain Analysis** · II | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQDbPR20RmomTrYpXVfy-sfBASs45z4V8pc1x0nU5uoz7mM?e=zOmWt5){.btn .btn-sm .btn-outline-primary} | |

## Week 8

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **March 1** | **Time Domain Analysis** · III | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQAuEVa_bcuHRKtNvXaUHRf-ARhVh4Bp-Xdz9jFK6BE_PWc?e=vgr9GX){.btn .btn-sm .btn-outline-primary} |
| **March 3** | **Time Domain Analysis** · IV | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQCVq_YlJ5oWRJSHyWkRVJcyAZKLZv7pZueHO0uGsh286nA?e=svpGPI){.btn .btn-sm .btn-outline-primary} | |
| **March 5** |  ·  |  | |

## Week 9

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **March 8** | **2nd Order System** · Zeros and Poles | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQDighffGzUOT525hcO9Z5V5AWGbbhikheduKTKDKfZ2Cbc?e=ePf8W1){.btn .btn-sm .btn-outline-primary} |
| **March 10** | **PID Controller​** ·  | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQD7b7gelnDeQpjNMdRcFq-QARDPHqarf2bGnQPjwy9l7Ak?e=cWYLPy){.btn .btn-sm .btn-outline-primary} | |
| **March 12** | **Stability​** · Routh Hurwitz  | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQAAg3ms6Hq8Tb_VGb9zmho-AaFGhTV7KIwRTjxNd7aiIio?e=ycKUoD){.btn .btn-sm .btn-outline-primary} | |

## Week 10

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **March 29** | **Root Locus** · I  | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQC7IQ8fqWLdTaR_IiV38fQOAXxHcOLC2l7UVfVdOtRstWY?e=MEPQDM){.btn .btn-sm .btn-outline-primary} | |
| **March 31** | **Root Locus** · II  | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQCnAOSIUxLmS756D1A4wMiDAYrP7YHiZluX81xXju5n_bU?e=0AVdro){.btn .btn-sm .btn-outline-primary} | |
| **April 2** | **Root Locus** · III  | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQBj8VpDmLJiT4QfEGGXHckFARa9HVlEuFAOMjT2rvpvnhE?e=HwFhk8){.btn .btn-sm .btn-outline-primary} | |

## Week 11

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **April 5** | **Root Locus** · IV | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQCnD_ZG35HyTLxWIAskCq6CAR-xs2QiG5uCK78W6kpE8kQ?e=QrBHmd){.btn .btn-sm .btn-outline-primary} | [Project M1 due](project.qmd){.btn .btn-sm .btn-danger} |
| **April 7** | **Root Locus** · V  | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQD_5BXBVNg-RbWTWdqYXL1WAe0uu6imEhSVbIIwSpBApDo?e=vXAZsZ){.btn .btn-sm .btn-outline-primary} | |
| **April 9** | **Review** ·  |  | |

## Week 12

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **April 12** | **Review** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary} | |
| **April 14** | **No Class** ·  | | |
| **April 16** | **PID** · Practical Issues | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQAlOWL0p6BfQIk15IMgB4fsAYheUHOR3oFFqwE2TxY_K7c?e=eQPORS){.btn .btn-sm .btn-outline-primary} | |

## Week 13

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **April 19** | **Lead Compensators using Root Locus** ·  | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQAPmOFYG-Y8TqbRGEM1KJVQAX4akI2QuaGvrAkGgxSC6Go?e=zNuD6x){.btn .btn-sm .btn-outline-primary} | [Project M2 due](project.qmd){.btn .btn-sm .btn-danger} |
| **April 21** | **Frequency Response Methods** ·  | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQBO3AYgjQk7SYRJEXF9627eAeG-uP53GqPl1Pm30tpa0-s?e=bf3RGp){.btn .btn-sm .btn-outline-primary} | |
| **April 23** | **Drawing the Bode Plots** ·  | [Slides (PDF)](https://kfupmedusa-my.sharepoint.com/:b:/g/personal/albeladi_kfupm_edu_sa/IQD2U6ezWoX-ToUDq3WT-1gNAWekcvpGrZx-ZaWVbvDguL4?e=fIegNf){.btn .btn-sm .btn-outline-primary} | |

## Week 14

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **April 26** | **** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary} | |
| **April 28** | **** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary} | |
| **April 30** | **** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary} | |

## Week 15

| Date | Topic | Materials | Deadlines |
|---|---|---|---|
| **May 3** | **** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary} | [Project Final Demo](project.qmd){.btn .btn-sm .btn-danger} |
| **May 5** | **** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary} | [Project Final Report due](project.qmd){.btn .btn-sm .btn-danger} |
| **May 7** | **** ·  | [Slides (PDF)](){.btn .btn-sm .btn-outline-primary} | |

::: {.callout-note appearance="minimal"}
### Notes
- If a slide link does not open, make sure you are logged in with your **KFUPM** account in the browser.
- The schedule may be adjusted; updates will be posted on the **Home → Announcements** section.
:::
